### ISSUE TITLE
tombstone the doc active revision conflict creates new revision in non active conflict

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/sync_gateway#3359]
### Sync Gateway version
2.0.0-821

### cbl ios build 
2.0.0-678

### Operating system
Centos

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,

            "server":"http://192.168.33.10:8091",
            "bucket":"travel-sample",
            "username":"travel-sample",
            "password": "password"
        }
    }
}


```

### Log output
https://gist.github.com/sridevi-15/56959e9aba242e05b7b62568dd19a942

### Steps to reproduce
1.  Crete docs in sg.
2. Create two conflcts in sg.
3. Updated doc in sg
4. Start replication to cbl and verify docs replicated
5. Update doc in cbl and continue replication.
graph for one of the doc looks like this :
<img width="1157" alt="screen shot 2018-03-07 at 11 13 29 am" src="https://user-images.githubusercontent.com/17035128/37112885-9e96739e-21f8-11e8-8935-e874325ca3f9.png">
 6. Tombstoned the doc which deletes active revision i.e 4-cd4f31b26cdf2664526acded48781ad18b52559c
Now the graph looks like this
  
<img width="1286" alt="screen shot 2018-03-07 at 11 14 13 am" src="https://user-images.githubusercontent.com/17035128/37112915-b4ae7384-21f8-11e8-9638-7b95a920f6a5.png">

Also updates done at step 3 (sg) and 5(cbl), I can see those updates when I get _all_docs rest API on sg.
{"_id":"sg_docs_0","_rev":"3-ad20fe895da2ee8e06fde89da15c4506ebeb645c","_revisions":{"ids":["ad20fe895da2ee8e06fde89da15c4506ebeb645c","41fa","a6014ad0cdb04db5f8b9fb881074bb74"],"start":3},"channels":["replication-channel"],"random":"33350bd3-d519-47ef-9e08-ee43d695a017",**"updates":1,"updates-cbl":1**}

### Expected behavior
It should not create a new revision on 2nd inactive conflict and should not see updates done by sg and cbl as updates done on only on active revision(2-41fa9b) and it got deleted. 

### Actual behavior
Create new revision for 2nd conflict

**Comment by sridevi-15** [comment]
cbl revs tree
./cblite revs /Users/sridevi.saragadam/Library/Developer/CoreSimulator/Devices/9E83DB6D-391D-4CB3-972D-3FDA93279BB7/data/Containers/Data/Application/0C1A6A13-1BD0-4690-8CB3-327EAFEBCA85/Library/Application\ Support/CouchbaseLite/cbl-test1520449663.68.cblite2 sg_docs_0
Document "sg_docs_0", current revID 3-ad20fe895da2ee8e06fde89da15c4506ebeb645c, sequence #24
* 1-a6014ad0cdb04db5f8b9fb881074bb74 (#1)
  * 2-41fa9b (#1)
    * 3-d1491ff7a80cd8d4ab0b45c6f04ca802 (#1)
      * 4-cd4f31b26cdf2664526acded48781ad18b52559c (#19), 84 bytes, KeepBody
        * 5-f823ecf2eb65a2aa49245d8745da44c69a447cab (#24), Deleted, Leaf
  * 2-41fa (#21)
    * 3-ad20fe895da2ee8e06fde89da15c4506ebeb645c (#24), 84 bytes, Leaf, KeepBody

**Comment by JFlath** [comment]
My read on this is that the spurious rev (`3-ad20fe...`) is coming from CBL.

Doc appears to be `sg_docs_0`. Tracing this through:

* It's created by `_bulk_docs`:

```
2018-03-06T19:53:04.566Z HTTP:  #004: POST /db/_bulk_docs (as autotest)
2018-03-06T19:53:04.568Z CRUD+: Invoking sync on doc "sg_docs_0" rev 1-a6014ad0cdb04db5f8b9fb881074bb74
2018-03-06T19:53:04.568Z CRUD:  Doc "sg_docs_0" in channels "{replication-channel}"
2018-03-06T19:53:04.568Z CRUD+: Saving doc (seq: #2, id: sg_docs_0 rev: 1-a6014ad0cdb04db5f8b9fb881074bb74)
2018-03-06T19:53:04.568Z DCP+: Persisting checkpoint for vbno 520
2018-03-06T19:53:04.568Z CRUD: Stored doc "sg_docs_0" / "1-a6014ad0cdb04db5f8b9fb881074bb74"
```

* It's updated twice to create the conflicts with `new_edits=false`:

```
2018-03-06T19:53:04.604Z HTTP:  #006: PUT /db/sg_docs_0?new_edits=false (as autotest)
2018-03-06T19:53:04.605Z CRUD+: Invoking sync on doc "sg_docs_0" rev 2-41fa
    :    :    :    :    :    :    :    : 
2018-03-06T19:53:04.631Z HTTP:  #008: PUT /db/sg_docs_0?new_edits=false (as autotest)
2018-03-06T19:53:04.631Z CRUD+: Invoking sync on doc "sg_docs_0" rev 2-41fa9b
```

* The "expected" revision `3-d1491f...` gets added via SG REST:

```
2018-03-06T19:53:05.339Z HTTP:  #048: PUT /db/sg_docs_0 (as autotest)
2018-03-06T19:53:05.339Z CRUD+: Invoking sync on doc "sg_docs_0" rev 3-d1491ff7a80cd8d4ab0b45c6f04ca802
```

* Revision `4-cd4f31...` gets added by replication from CBL:

```
2018-03-06T19:53:07.737Z SyncMsg: [2a78780e] #015: Type:rev Id:sg_docs_0 Rev:4-cd4f31b26cdf2664526acded48781ad18b52559c Sequence:19  User:autotest
    :    :    :    :    :    :    :    : 
2018-03-06T19:53:07.741Z CRUD+: Invoking sync on doc "sg_docs_0" rev 4-cd4f31b26cdf2664526acded48781ad18b52559c
```

* Revision `4-cd4f31...` is deleted via SG REST, creating the tombstone `5-777289...`:

```
2018-03-06T19:53:09.986Z HTTP:  #069: DELETE /db/sg_docs_0?rev=4-cd4f31b26cdf2664526acded48781ad18b52559c (as autotest)
2018-03-06T19:53:09.987Z CRUD+: Invoking sync on doc "sg_docs_0" rev 5-777289db93beae39df76003b45e89696
```

* The remaining current rev, `2-41fa`, then gets sent to CBL:

```
2018-03-06T19:53:10.041Z Changes+: MultiChangesFeed sending {Seq:52, ID:sg_docs_0, Changes:[map[rev:2-41fa]], branched:true}   (to autotest)
    :    :    :    :    :    :    :    : 
2018-03-06T19:53:10.046Z Sync+: [2a78780e] Sending rev "sg_docs_0" 2-41fa based on 1 known.  User:autotest
```

* It then looks like CBL makes a change on to of this revision and that gets pushed back as `3-ad20fe...`:

```
2018-03-06T19:53:10.149Z SyncMsg+: [2a78780e] #027: Type:proposeChanges   --> OK Time:1.804985ms User:autotest

2018-03-06T19:53:10.152Z SyncMsg: [2a78780e] #028: Type:rev Id:sg_docs_0 Rev:3-ad20fe895da2ee8e06fde89da15c4506ebeb645c Sequence:24  User:autotest
2018-03-06T19:53:10.153Z CRUD+: Invoking sync on doc "sg_docs_0" rev 3-ad20fe895da2ee8e06fde89da15c4506ebeb645c
2018-03-06T19:53:10.153Z CRUD+: Saving old revision "sg_docs_0" / "2-41fa" (70 bytes)
```

---

At a guess, it looks like either:

* Things are working as expected, and the CBL test case is updating things more than you expect
* CBL is doing some strange resolution code and adding a spurious revision to that branch.

Either way, I suspect the CBL test case/code will help here.

**Comment by tleyden** [comment]
From the Steps to reproduce:

> 3. Updated doc in sg

Can you add more details on this update?  Eg, the REST call params which should show which revision is being updated.

**Comment by tleyden** [comment]
From @adamcfraser on hipchat:

1. Sync Gateway has doc in conflict, only sends winning revision to Lite (3-d14)
2. CBL updates, pushes to SG, both SG and CBL now have 4-cdf
3. Sync Gateway tombstones the rev (creates 5-777 on server), and old conflict becomes active (2-41fa)
4. Sync Gateway sends 2-41fa to CBL

At this point Lite treats as a conflict (it doesn't know about 5-777), and so merges and generates a new rev

**Comment by pasin** [comment]
I think @JFlath is right. There is something strange going on with the conflict resolution. I think this is happening based on my understanding:

1. After `4-cd4f31` is tombstoned on the SG, `3-ad20fe` branch became a new winning branch. That is sent to CBL.
2. CBL still has `4-cd4f31` branch which will be conflicted with the `3-ad20fe` branch. CBL will pick `4-cd4f31` as a winning but it will also tombstone `4-cd4f31` branch as it is a local branch. I would expect a new branch with the same content as `4-cd4f31` created under `3-ad20fe`.

**Comment by sridevi-15** [comment]
Test code is here : https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L1610

test_default_conflict_with_two_conflictsAndTomstone

Tested on iOS and Android and see same issue

**Comment by adamcfraser** [comment]
@pasin I think your description is correct, with some slight differences:
1. After `4-cd4f31` is tombstoned on the SG, `**2-41fa**` branch became a new winning branch. That is sent to CBL.
2. CBL still has `4-cd4f31` branch which will be conflicted with the `**2-41fa**` branch. CBL will pick `4-cd4f31` as a winning but it will also tombstone 4-cd4f31 branch as it is a local branch. I would expect a new branch with the same content as 4-cd4f31 created under `**2-41fa**`.

This all seems to be happening - CBL creates the new rev `3-ad20fe` and pushes it to SG.  

Functionally I think this is bad - CBL is resurrecting the rev that has already been tombstoned by SG.

Any ideas on how SG can communicate to CBL information about the tombstone `5-7772` along with `2-41fa`?

**Comment by pasin** [comment]
Just an idea, can SG send a deleted revision first and then send the new winning revision for the case of there is a new winning revision after tombstoning?

**Comment by pasin** [comment]
@snej what is your thought on this case?

**Comment by borrrden** [comment]
It sounds a lot like that one, and I thought so too at first but it's different.  The issue is SG never sends the complete tree with the final deletion and so CBL is fooled into thinking there is a conflict when there isn't (since it only has 4 out of the 5 entries in the "closed" tree, it will think that the tree is still "open")

**Comment by snej** [comment]
I think LiteCore can handle this situation by detecting that the incoming current revision isn't a child of the previously-known server-side current revision. In that case a branch-switch has occurred on the server, so it should just move the current-server-revision marker.

**Comment by borrrden** [comment]
Does LiteCore have this information?  All it knows it "winning" and "losing".  Is that enough?

**Comment by sridevi-15** [comment]
Can you please let me know which ios and android builds have this fix, I can test

**Comment by snej** [comment]
I just pushed the fix (I hope) to LiteCore.

**Comment by snej** [comment]
...and to CBL-iOS (commit c9c8940e). So the next build should have it.

**Comment by pasin** [comment]
@sridevi-15 Could you please verify the fix with CBL iOS Build 697?

**Comment by sridevi-15** [comment]
@pasin , @snej , what is the expected behavior for this after the fix . I still see the tombstoned revision by sg still exists in cbl, 
Current revision tree of sg and cbl looks like this , which seems like expected. 

### cbl revision tree : 
./cblite revs /Users/sridevi.saragadam/Library/Developer/CoreSimulator/Devices/9E83DB6D-391D-4CB3-972D-3FDA93279BB7/data/Containers/Data/Application/DBB4A27A-029A-4632-8295-BEF72AE5F752/Library/Application\ Support/CouchbaseLite/cbl-test1520894540.4.cblite2 sg_docs_0
Document "sg_docs_0"
 * 1-a6014ad0cdb04db5f8b9fb881074bb74             ------ #2
   * 2-41fa9b                                     ------ #2
     * 3-3096fa451349dda37589d2991b99ca16         ------ #2, 80 bytes
       * 4-76a1cc322dc13448f323b18f2ac793e55417026f----KL #19, 84 bytes  [CURRENT]

### sg revision tree : 
<img width="687" alt="screen shot 2018-03-12 at 3 56 25 pm" src="https://user-images.githubusercontent.com/17035128/37313786-f8d7beda-260d-11e8-919b-993b9bd876f7.png">

After the fix, tomstoned revision by sg does not effect cbl ?

**Comment by pasin** [comment]
@sridevi-15 Can you post the revision tree on CBL side before the last pull? It seemed like the rev-ids are not the same as the original post anymore.

**Comment by borrrden** [comment]
> I still see the tombstoned revision by sg still exists in cbl

But then you posted a revision tree without it?

**Comment by borrrden** [comment]
Here is what I have found.  For document sg_docs_0:

Before the SG delete:
```
Document "sg_docs_0", current revID 4-f8b1cf95fe3a8fd6ff1dabc441ab2151bdbc77b4, sequence #17
* 1-a6014ad0cdb04db5f8b9fb881074bb74 (#3)
  * 2-41fa9b (#3)
    * 3-2896c8cd50c0eda24ef369fd74e37f06 (#3), 80 bytes
      * 4-f8b1cf95fe3a8fd6ff1dabc441ab2151bdbc77b4 (#17), 84 bytes, Leaf, KeepBody
```

After the SG delete:
```
Document "sg_docs_0", current revID 2-41fa, sequence #21
* 1-a6014ad0cdb04db5f8b9fb881074bb74 (#3)
  * 2-41fa (#21), 34 bytes, Leaf, KeepBody
```

This seems like the expected behavior.

**EDIT** This was run against .NET

**Comment by sridevi-15** [comment]
I have tested in DI mode , due to delay with sg accel , I did not get expected behavior. I reran test with cc and it works fine. Tested on ios build 702 and android 427
